DNM: remove CleavingContext.replication_count
CleavingContext instances are constructed using key-value pairs that
are decoded from JSON blobs persisted in container metadata. If the
CleavingContext interface changes then it is possible for the
persisted JSON to have obsolete key-value pairs that will be passed to
the CleavingContext constructor. Previously this would result in a
traceback and prevent cleaving progress, e.g:

TypeError: CleavingContext.__init__() got an unexpected keyword \
    argument 'replication_count'

With this patch, the `replication_count' kwarg will be removed when
constructing a CleavingContext.

To the best of the author's knowledge no arguments have been removed
from the CleavingContext interface in any *recent* release.  However, an
experimental additions to the interface was carried in a downstream
releases, and the arguments subsequently removed from the interface [1].
This has resulted in obsolete key-value pairs being persisted to
container metadata (but only in our environment). This patch is
therefore remedial and not necessary upstream.

[1] Related-Change: I4ad1e22fd011652d80269a76353e5fc14db249f5
    (patchset 37 vs patchset 38)

Change-Id: Ic3ea785dd902c51bd7a112716f0f98f012050dec
Signed-off-by: Clay Gerrard <clay.gerrard@gmail.com>
Signed-off-by: Christian Ohanaja <cohanaja@nvidia.com>
Signed-off-by: Jianjian Huo <jhuo@nvidia.com>