Fix sharder.sharding.completed timing metric
When a sharder finishes sharding it using the epoch Timestamp to
calculate how long it took to complete sharding. But the
logger.timing_since method takes a float (time.time()) not a timestamp.
This causes tracebacks with:

  return self.timing(metric, (time.time() - orig_time) * 1000,#012
  TypeError: unsupported operand type(s) for -: 'float' and 'Timestamp'

In a python shell we can see this:

  from swift.common.utils import Timestamp
  ts = Timestamp.now()
  ts
  1684474287.80183_0000000000000000
  time.time() - ts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    TypeError: unsupported operand type(s) for -: 'float' and 'Timestamp'
  time.time() - float(ts)
  19.668439626693726

This patch makes the timing_since method support support Timestamp
objects.

Change-Id: I6501284e8b749be4efd4e3257945b56933c619d2