swift_proxy: add memcache skip success/error stats for shard range.
This patch will add more granularity to shard operation cache or
backend metrics, and then remove some of existing and duplicated
metrics.

Before this patch, related metrics are:
  1.shard_<op>.cache.[hit|miss|skip]
  2.shard_<op>.backend.<status_int>
where op is 'listing' or 'updating'.

With this patch, they are going to become:
  1.shard_<op>.infocache.hit
    cache hits with infocache.
  2.shard_<op>.cache.hit
    cache hits with memcache.
  3.shard_<op>.cache.[miss|skip|force_skip|disabled|error].<status_int>
    Those are operations made to backend due to below reasons.
      miss: cache misses.
      skip: the selective skips per skip percentage config.
      force_skip: the request with 'x-newest' header.
      disabled: memcache is disabled.
      error: memcache connection error.
    For each kind of operation metrics, suffix <status_int> will
    count operations with different status. Then a sum of all
    status sub-metrics will the total metrics of that operation.

UpgradeImpact
=============
Metrics dashboard will need updates to display those changed metrics
correctly, also infocache metrics are newly added, please see above
message for all changes needed.

Co-Authored-By: Clay Gerrard <clay.gerrard@gmail.com>
Change-Id: Ib8be30d3969b4b4808664c43e94db53d10e6ef4c